service: rest-api

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

plugins:
  - 'serverless-offline'
	
functions:
  units:
    handler: 'index.handler'
    events:
      - http:
          path: '/api/{proxy+}'
          method: any